### ISSUE TITLE
Enhance TV input type "Date"

### ISSUE THREAD

**Issue by labr1005** [modx-ccc-2015/whishlist#15]
Add an option to disable/hide the time selection.
![bildschirmfoto 2015-01-18 um 12 04 16](https://cloud.githubusercontent.com/assets/1913250/5792162/ca5d5930-9f0a-11e4-894e-30458015017d.png)

**Comment by mindeffects** [comment]
Yes, please! I often have to use "date only" and would love to hide the "time" from the users (setting it internally to a fixed value, like 00:00 to make comparisons with current time work, like "is release date=today").
Maybe a sort of date-string to format the output would be nice, like "d-m-Y".

**Comment by rtripault** [comment]
Just to add, Revo makes use of the custom `xdatetime` xtype (ExtJS), which ships the "hour" stuff. ExtJS have a native "date only" xtype : `datefield` ([doc](http://docs.sencha.com/extjs/3.4.0/#!/api/Ext.form.DateField)).

The "output" could be an option (and i feel like the "proper" way to go), according we store a timestamp in the DB.

Do you guys think that should be shipped into the code or as a third party package/custom TV ?

**Comment by wuuti** [comment]
Core code.

**Comment by mindeffects** [comment]
Core code, please!
Also look at: #51 "DateTV with input options"

**Comment by pepimpepa** [comment]
I hide the time, it will need probably to create completely new TV only with date...
