### ISSUE TITLE
@theboxer: New option to redirect a "Collection-Resource" to a specific child/id

### ISSUE THREAD

**Issue by JensWolff** [modx-ccc-2015/whishlist#20]
It would be very nice, if you can redirect the Collection-Resource to a specific ID (like the document-type "Weblink"). Sometimes the collection itself is just a folder, but there is no "real site" at the frontend. So if you could add an option to add a redirect to another resource (like: [[~6]]) it would be awesome. If the text-field is empty, the collections gets shown as a normal "document/resource" and if you fill something into the field, it redirects to the value.

**Comment by theboxer** [comment]
Why you don't use redirect snippet for this?

**Comment by JensWolff** [comment]
Thats the way I fixed my problem at the moment, but perhaps it would be a great feature. Thats why I have postet it ;-)

**Comment by theboxer** [comment]
I would stick to this solution and don't add unnecessary features to Collections...

**Comment by JensWolff** [comment]
OK
