### ISSUE TITLE
Content-field hideable by option in the template-editing-interface

### ISSUE THREAD

**Issue by JensWolff** [modx-ccc-2015/whishlist#27]
A checkbox "hide content field" as option in the template-editing-interface, which allows it, to completely hide the content-field on every resource that uses this template. This would be very usefull for ressources that do not use the content-field at all (and gets only generated by template-variables for example).

**Comment by mindeffects** [comment]
+1
The "content" field is nice but in so many cases nothing more then another field among many content fields AKA TVs.
I use "content" as an agregator field for SimpleSearch to store only the "should be visible" content. An easy "hide content" option would come in very handy.
Don't forget to check out the upcoming SimpleSearch v1.9.2 by @TheBoxer. He did an awesome job!

**Comment by labr1005** [comment]
Hm, this can really easily be done with form customization... Too many clicks for you?

**Comment by mindeffects** [comment]
Manager customization (FKA form customization) is the way I go for now. But MC is far from enabling a propper UI design and should be way more integrated into the template organization. But THAT is a very different story/issue.

**Comment by JensWolff** [comment]
@labr1005 Could that also be done for a specific template via form customization? Or just in general?

**Comment by theboxer** [comment]
I agree with @labr1005, this is really easy to do with form customisations and having another setting for that is useless. This time it's content, next time it will be description, long title, introtext, alias, etc.

@JensWolff yes, you can set FC to be applied only on specific template, so you will achieve what you proposed above.

**Comment by labr1005** [comment]
@JensWolff Yes, you can define a specific template and even combine this with more constrain fields.
![bildschirmfoto 2015-01-19 um 10 57 27](https://cloud.githubusercontent.com/assets/1913250/5798852/f4ee0822-9fcb-11e4-954f-28eb8041b1c5.png)

**Comment by mindeffects** [comment]
@JensWolff: Then you/we could close this issue. Right? ;-)

**Comment by JensWolff** [comment]
@labr1005 @TheBoxer Thanks, thats all what @mindeffects and I wanted.. So this issue is closed ;-)
