### ISSUE TITLE
Having fun, hacking a lot, socializing even more

### ISSUE THREAD

**Issue by wuuti** [modx-ccc-2015/whishlist#32]
Well, this is an open whishlist for the CCC, isn't it? My wishes/feelings on a meta base:
- I hope to get to know some of you better
- I am excited to learn a lot of new stuff
- I am happy to have the chance to teach someone something I am good at
- I am glad to be part of an open source meeting 
- I am looking forward to have some beer with you in the evening at the famous party mile around the location :-)

And you?

**Comment by DESIGNfromWITHIN** [comment]
100% agree! I am really excited about this event! 

I might be one of the few Front End guys so hope to be able to help and learn more about the back end stuff!

**Comment by wuuti** [comment]
We did it! Experimental hacking meetup finished. Thanks to all attendees. I hope we will see each other in the near future again. Is it getting viral around europe???
