### ISSUE TITLE
TLC for manager's profile page

### ISSUE THREAD

**Issue by rtripault** [modx-ccc-2015/whishlist#35]
If you go to `?a=security/profile`, the options are rather "thin".

It should be possible for the user to set/define a bunch a user settings (allowed/defined by the developer), like : 
- `manager_language` which would allow the user to define her own UI language
- `confirm_navigation` which would allow the user to define if she wants to be notified when leaving a resource "form" with unsaved changes

**Comment by JensWolff** [comment]
+1 nice one!

**Comment by inreti-sb** [comment]
Sehr geehrte Damen und Herren,

bis einschließlich 24.09.2016 bin ich nicht zu erreichen. Ihre E-Mails werden von mir erst nach meiner Rückkehr gelesen und bearbeitet. 

Im Notfall folgen Sie bitte diesem Link:
https://www.inreti.de/notfall.html

Mit freundlichen Grüßen
Sebastian Burchert
