### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by rtripault** [modx-ccc-2015/whishlist#36]
Last "real" test was commit in December 2011 (see [history on master branch](https://github.com/modxcms/revolution/commits/master/_build/test)).

Investing in unit testing would prevent some regression, especially with the contributors growth.

Once again, this won't directly bring "features" to developers/users, but should ease contributions integration, iteration... plus i've eard that's cool to have unit tests ^^

**Comment by pixelfanatiker** [comment]
Well, it can be a good idea, to have unit tests for the core classes...
