### ISSUE TITLE
ACL for specific (lexicon) namespaces

### ISSUE THREAD

**Issue by bequadrat** [modx-ccc-2015/whishlist#47]
It's currently not possible to let a client edit lexicon entries and/or system settings only for one namespace (or a list of namespaces).

I often create namespaces just for client-specific lexicons (to store strings that are reused multiple times on a website, which is even more practical with multi-language websites), and I cannot give my client access to those lexicon entries without giving him permission to all the other lexicons. Same goes with system settings.

The "Creative Freedom" of MODX currently ends here :-) It's all or nothing and should be more granular. So it'd be a great enhancement to have ACLs for that, like we already have for resource groups for example.

**Comment by mindeffects** [comment]
Basically everybody doing a multilanguage websites is in need of that! I proposed this feature aged ago. ay

Yesterday I chatted with @TheBoxer on that topic and he told me that he wanted to extend the groups permissions. This way it would be just filtering and display only the granted lexicons in the manager.
Furthermore it would allow the restriction of e.g. system settings or basically all the namespace depending stuff.

I would love to see that happening at CCC! :-)

**Comment by rtripault** [comment]
Keep in mind that while groups seems to be a good idea, it would mean that you will have to put all **restricted** namespaces (non editable) into a "restricted" group.
Additionally, all new namespaces added after group creation/assignation would be editable.

But i have nothing against the idea ;)

**Comment by bequadrat** [comment]
I thought that you'd like that @mindeffects :-)

**Comment by mindeffects** [comment]
It is only a "manager display thing", @rtripault, as with Form (Manager) Cusomization. Or good ol' Apache's "deny from all" and "allow from xyz".
The core should not be affected, _only_ the manager.

**Comment by mindeffects** [comment]
See: [MODX issue #11448: Assign Namespaces to a Category](https://github.com/modxcms/revolution/issues/11448)
Label: **priority-2-high**!

**Comment by wuuti** [comment]
Another one that can be marked as closed, I believe... :-)

**Comment by mindeffects** [comment]
That ... would ... be ... AWESOME! Have to check it out!
