### ISSUE TITLE
Choosing a template BEFORE a resource is created

### ISSUE THREAD

**Issue by mindeffects** [modx-ccc-2015/whishlist#54]
Normally you create a resource and the first thing you do is set a correct template, because it is often the correct one. This change always takes some time.
Before a resource is created, the user should be ask which template should be used – also when duplicating a resource.
I help myself be using [defaultTemplateByParentTv.plugin](https://gist.github.com/boundaryfunctions/1474540) but this is not exactly what I want. MODX shall ask what kind of page should be created. A default is nice, but it cannot be changed to another template before the resource is created.

**Comment by DESIGNfromWITHIN** [comment]
+1 this would make creating pages for non-technical clients more intuitive.

**Comment by bequadrat** [comment]
**Done and working!**
See: https://github.com/bequadrat/modx-template-select

This certainly needs some polish (especially internationalisation is a bit "hacky"). Maybe someone more experienced can show me how to make a package out of this? :-)

**Comment by bartholomej** [comment]
It works! GJ :+1:

**Comment by bequadrat** [comment]
I cleaned a few things up, made a package with PackMan and submitted it to the MODX package provider.

**Comment by pepimpepa** [comment]
Great! It can help a lot! Is there some option i.e. if the parent is template ID (5) then user can choose from template ID 3,6,7?

**Comment by JensWolff** [comment]
:+1:

**Comment by bequadrat** [comment]
@pepimpepa There are currently no options. But it uses the same MODExt control that is used by the resource editor. So there is a good chance that TemplateSelect will respect the same rules. Go, give it a try! :-)
