### ISSUE TITLE
Autogenarating aliases only works if FURL is also active

### ISSUE THREAD

**Issue by mindeffects** [modx-ccc-2015/whishlist#56]
When "autogenerate alias" is set to "on", nothing will happen to your alias until you also set "use FURL". So, when you are nearly finished with your 589 resources, you don't have a single auto-generated alias. When you turn FURL on, you have some work ahead of you ...
Why?
I would like "auto generate alias" to work as it says: generate an alias, no matter if FURL is turned on or off.

**Comment by JensWolff** [comment]
@mindeffects I think the title of this wish is not correct  "Remote Monitoring for all those MODX installations out there "in the field"" :P

**Comment by mindeffects** [comment]
Thanks, @JensWolff . I changed the title.

**Comment by Mark-H** [comment]
https://github.com/modxcms/revolution/pull/11505

Did you forget already? :(

**Comment by mindeffects** [comment]
In any case: Yes, I forgot. :-(
I don't recall exactly but I worked on a MODX site a few days ago and had some trouble with aliases. Need to check if it was 2.2.16 or 2.3.2.
Anyhow, thanks for fixing it!
