### ISSUE TITLE
New "OnSnippetNotFound" and "OnChunkNotFound"-system-events for custom development

### ISSUE THREAD

**Issue by JensWolff** [modx-ccc-2015/whishlist#8]
There is actually no event that fires, if the snippet you want to call was not found. It would be nice if you can dynamicly loads snippets from a external database or from files which are actually not saved as snippet in the system. The same for Chunks and perhaps all the other element-types.

**Comment by rtripault** [comment]
I guess the `OnElementNotFound` event (see [code](https://github.com/modxcms/revolution/blob/master/core/model/modx/modparser.class.php#L564)) should do the trick, don't you think ?

**Comment by JensWolff** [comment]
@rtripault Thanks, that seems to be what I've searched and missed ;-)
